#!/bin/bash

CUR_DIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)
NVIM_DIR=$(cd ${CUR_DIR}/..; pwd)

alias Y="source ${CUR_DIR}/bashrc"
alias ybashrc="nvim ${CUR_DIR}/bashrc"
alias ynvimrc="nvim ${NVIM_DIR}/init.lua"
alias ynvimup="cd ${NVIM_DIR}; git pull; cd - >/dev/null"
alias cdypack="cd ${NVIM_DIR}/pack/packer/start"
